# -*- coding: utf-8 -*-
"""Python lesson 35.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Eo7JmaHIdV_xzIAHjkDj_cWtS7HIsEzJ
"""

class Book:
    library_name = "Central Library"  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author

    def show_library(self):
        print(self.library_name)  # доступ через self
        print(Book.library_name)  # доступ через имя класса

print(Book.library_name)  # доступ через класс
book = Book("1984", "George Orwell")
print(book.library_name)  # доступ через объект
book.show_library()       # доступ изнутри

class Book:
    library_name = "Central Library"  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author

print(Book.library_name)

book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")
Book.library_name = "City Library"
print(Book.library_name)
print(book.library_name)      # у объекта тоже изменилось
print(book2.library_name)     # у объекта тоже изменилось

class Book:
    library_name = "Central Library"  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author

book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")

book.library_name = "Private Shelf"  # создаёт новое поле в book
print(book.library_name)  # Private Shelf — новое значение в объекте
print(Book.library_name)  # поле класса не изменилось
print(book2.library_name) # также прочитает поле класса

class Book:
    library_name = "Central Library"  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author

book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")

book.library_name = "Private Shelf"  # создаёт новое поле в book
book.new = "new value"  # создаёт новое поле в book

print(book.__dict__)  # у book1 появилось собственное поле
print(book2.__dict__) # у book2 такого поля нет
print(Book.__dict__)  # поля и методы класса

class Book:
    library_name = "Central Library"  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author

book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")

book.book_color = "black"            # создание поля объекта вне класса
Book.default_language = "eng"        # создание поля класса вне класса
print(book.book_color)
# print(book2.book_color)            # ошибка, такого поля нет
print(book.default_language)

class Book:
    def __init__(self, title, author, language="English"):
        self.title = title
        self.author = author
        self.language = language

# язык по умолчанию
book1 = Book("1984", "George Orwell")
# другой язык
book2 = Book("Cien años de soledad", "Gabriel García Márquez", "Spanish")

print(book1.language)
print(book2.language)

class Book:
    total_books = 0  # поле класса

    def __init__(self, title, author):
        self.title = title
        self.author = author
        Book.total_books += 1

    @classmethod
    def show_total(cls):
        print(f"Total books: {cls.total_books}")
        # print(cls.title)  # Нельзя обратиться к полю объекта

Book.show_total()     # Вызов через класс
book1 = Book("1984", "George Orwell")
Book.show_total()     # Вызов через класс
book2 = Book("Brave New World", "Aldous Huxley")

Book.show_total()     # Вызов через класс
book1.show_total()    # Вызов через объект

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    @classmethod
    def from_string(cls, data):
        title, author = data.split(" - ")
        # cls — это Book, поэтому cls(title, author) эквивалентно Book(title, author)
        return cls(title, author)  # создаёт и возвращает новый объект

book = Book.from_string("1984 - George Orwell")
print(book.title)
print(book.author)

class Book:
    default_format = "PDF"
    default_language = "en"

    @classmethod
    def show_defaults(cls):
        print(f"Format: {cls.default_format}, Language: {cls.default_language}")

    @classmethod
    def reset_defaults(cls):
        cls.default_format = "PDF"
        cls.default_language = "en"

Book.default_format = "EPUB"  # Изменение формата
Book.show_defaults()          # Просмотр текущих настроек
Book.reset_defaults()         # Сброс до базовых настроек
Book.show_defaults()          # Просмотр текущих настроек

class Book:
    def __init__(self, title):
        self.title = title

    @staticmethod
    def is_title_valid(title):
        return isinstance(title, str) and len(title) > 0
        # return len(title) > 0 and isinstance(title, str)

print(Book.is_title_valid("1984"))       # True
print(Book.is_title_valid(""))           # False
print(Book.is_title_valid(123))          # False

if Book.is_title_valid("1984"):
    book = Book("1984")
    print(book.title)

class MathHelper:
    @staticmethod
    def square(x):
        return x * x

    @staticmethod
    def cube(x):
        return x * x * x

print(MathHelper.square(5))
print(MathHelper.cube(3))

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author


book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")

print(book)
print(book2)

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def __str__(self):
        return f"{self.title} by {self.author}"

book = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")

print(book)
print(str(book2))

l = [book, book2]
print(l)

l = [str(book), str(book2)]
print(l)

print(book.__str__())

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def __str__(self):
        return f"{self.title} by {self.author}"

    def __repr__(self):
        return f"Book(title={self.title}, author={self.author})"
        # return f"Book(title={self.title!r}, author={self.author!r})"

book1 = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")
print(repr(book1))
books = [book1, book2]
print(books)
print(book)

class Book:
    def __init__(self, title, author):
        self.title = title
        self.author = author

    def __str__(self):
        return f"{self.title} by {self.author}"

    def __repr__(self):
        # return f"Book(title={self.title}, author={self.author})"
        return f"Book(title={self.title!r}, author={self.author!r})"

book1 = Book("1984", "George Orwell")
book2 = Book("Brave New World", "Aldous Huxley")
print(repr(book1))
books = [book1, book2]
print(books)
print(book)

new_book = Book(title='1984', author='George Orwell')
print(new_book)