# -*- coding: utf-8 -*-
"""Python lesson 36.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WnPL1ysEe8z9iQwqGQtPVcdJEWtrTLtD
"""

class Employee:
    def __init__(self, name):
        self.name = name

    def work(self):
        print(f"{self.name} is working...")

class Programmer(Employee):
    pass

class Manager(Employee):
    pass

programmer = Programmer("Alice")
manager = Manager("Bob")

programmer.work()
manager.work()

class Employee:
    def __init__(self, name):
        self.name = name

    def work(self):
        print(f"{self.name} is working...")

class Programmer(Employee):
    def __init__(self, job):
        self.job = job

class Manager(Programmer):
    pass

# programmer = Programmer("Alice")
manager = Manager("Bob")

# programmer.work()
# manager.work()
# manager.name

# class Math:
#     def add(self, a, b):
#         return a + b

#     def add(self, a, b, c):
#         return a + b + c

# m = Math()
# print(m.add(1, 2, 3))   # Работает
# print(m.add(1, 2))      # Ошибка!

class Employee:

    def __init__(self, name):
        self.name = name

    def work(self):
        print(f"{self.name} is working...")

class Programmer(Employee):
    def work(self):
        print(f"{self.name} writing code...")

class Manager(Employee):
    pass
    # def work(self):
    #     print(f"{self.name} managing team...")


staff = [Employee("Alice"), Manager("Bob"), Programmer("Bill")]

for person in staff:
    person.work()  # Поведение зависит от конкретного типа

# class Employee:
#     def work(self):
#         print("Employee is working")

# class Manager():
#     pass

# person = Manager()
# person.work()

class Employee:
    def __init__(self, name):
        self.name = name

class Programmer(Employee):
    def __init__(self, name, language):
        # повторяем то же, что уже делает родитель
        self.name = name
        self.language = language

class Manager(Employee):
    def __init__(self, name, department):
        self.name = name  # снова повторяем
        self.department = department

# class Employee:
#     def __init__(self, name):
#         self.name = name

# class TechnicalWorker(Employee):
#     def __init__(self, name, department):
#         # явный вызов родителя
#         Employee.__init__(self, name)
#         self.department = department

# class Programmer(TechnicalWorker):
#     def __init__(self, name, department, language):
#         # явный вызов родителя
#         Employee.__init__(self, name)
#         self.language = language

# p = Programmer("Alice", "develop", "Python")
# print(p.name, p.language)
# print(p.department)

class Employee:
    def __init__(self, name):
        self.name = name

class TechnicalWorker(Employee):
    pass
    def __init__(self, name):
        # явный вызов родителя
        super().__init__(name)
        self.new = "new"

class Programmer(TechnicalWorker):
    def __init__(self, name, language):
        super().__init__(name)  # вызываем родительский __init__
        self.language = language

class Manager(TechnicalWorker):
    def __init__(self, name, department):
        super().__init__(name)  # вызываем родительский __init__
        self.department = department

p = Programmer("Alice", "Python")
print(p.name)
print(p.language)
# print(p.new)

class Person:
    def __init__(self, name):
        self.name = name
        print(f"Init Person: {self.name}")

class Employee(Person):
    def __init__(self, name):
        super().__init__(name)
        print("sdsdfsd")
        # self.name = name
        # print(f"Init Person: {self.name}")

    def work(self):
        print(f"{self.name} is working...")


class Manager(Employee):
    def __init__(self, name, department):
        super().__init__(name)
        self.department = department
        print(f"Init Manager: {self.name} manages {self.department}")

m = Manager("Alice", "Development")

m.work()

class Employee:
    def work(self):
        print("Employee is doing general tasks.")

class Programmer(Employee):
    def work(self):
        super().work()  # вызываем метод родителя
        print("Programmer is writing code.")

class Manager(Employee):
    def work(self):
        super().work()
        print("Manager is holding a meeting.")

staff = [Programmer(), Manager()]
for person in staff:
    person.work()
    print()

class Person:
    pass
    def __init__(self, name):
        self.name = name
        print(f"Init Person: {self.name}")

p = Person("Alice")
print(p.__str__())
print(str(p))

class Person:
    pass


p = Person()
print(p.__str__())
print(str(p))

class Book(object):
    pass

class Book:
    pass

class Employee:
    pass

class Programmer(Employee):
    pass

class Manager(Employee):
    pass

e = Employee()
p = Programmer()
m = Manager()

print(isinstance(p, Programmer))  # экземпляр класса
print(isinstance(p, Employee))    # экземпляр наследника
print(isinstance(p, Manager))     # Manager не находится выше в иерархии
print(isinstance(p, object))      # True — все классы наследуют от object

class Employee:
    def work(self):
        print("Выполняет общие задачи")

class Programmer(Employee):
    def write_code(self):
        print("Пишет код")

class BackendDeveloper(Programmer):
    def write_code(self):
        print("Пишет серверный код")

class FrontendDeveloper(Programmer):
    def write_code(self):
        print("Пишет интерфейс")

class Manager(Employee):
    def work(self):
        print("Проводит собрание")


staff = [
    Programmer(),
    BackendDeveloper(),
    FrontendDeveloper(),
    Manager(),
    Employee()
]

for person in staff:
    if isinstance(person, Programmer):
        person.write_code()
    else:
        person.work()

# Строка принадлежит к одному из классов
print(isinstance("hello", (str, int)))
print(isinstance("hello", (Programmer, Manager)))

class Employee:
    pass

class Programmer(Employee):
    pass

class Manager(Employee):
    pass

class BackendDeveloper(Programmer):
    pass

print(issubclass(Programmer, Employee))         # Прямой потомок
print(issubclass(BackendDeveloper, Programmer)) # Прямой потомок
print(issubclass(BackendDeveloper, Employee))   # Потомок через цепочку
print(issubclass(Manager, Programmer))          # Разные ветки иерархии
print(issubclass(Employee, object))             # Все классы наследуются от object

class Employee:
    def send_welcome_email(self):
        print("Добро пожаловать в компанию!")

class Programmer(Employee):
    def send_welcome_email(self):
        print("Добро пожаловать, разработчик! Не забудьте подключиться к репозиторию.")

class Manager(Employee):
    pass
    # def send_welcome_email(self):
    #     print("Добро пожаловать, менеджер! Сегодня у вас первое собрание с командой.")


def hire_employee(cls):
    if not issubclass(cls, Employee):
        raise ValueError("Можно нанимать только классы, основанные на Employee")

    person = cls()
    person.send_welcome_email()

hire_employee(Programmer)
hire_employee(Manager)
# hire_employee(str)  # ValueError: Не наследник Employee